import { Satellite, Alert, GroundStation, HealthStatus } from '../types/telemetry';

export const INITIAL_GROUND_STATIONS: GroundStation[] = [
  { id: 'GS-MADRID', name: 'GS-Madrid', location: 'Madrid, Spain', lat: 40.4168, lon: -3.7038, status: 'Active' },
  { id: 'GS-DELHI', name: 'GS-New Delhi', location: 'New Delhi, India', lat: 28.6139, lon: 77.2090, status: 'Active' },
  { id: 'GS-SINGAPORE', name: 'GS-Singapore', location: 'Singapore', lat: 1.3521, lon: 103.8198, status: 'Active' },
  { id: 'GS-NEWYORK', name: 'GS-New York', location: 'New York, USA', lat: 40.7128, lon: -74.0060, status: 'Active' },
];

export const INITIAL_SATELLITES: Satellite[] = [
  {
    id: 'SAT-001',
    name: 'AGIS-3',
    noradId: 43205,
    callsign: 'AG-03',
    orbitType: 'LEO',
    overallHealth: 96,
    healthStatus: 'nominal',
    position: { x: 4.2, y: 1.5, z: 0.8 },
    orbitRadius: 4.5,
    orbitSpeed: 0.008,
    orbitAngle: 0.2,
    inclination: 51.6,
    aiAnomaly: {
      detectedAnomaly: 'NO ANOMALY DETECTED',
      severity: 'LOW',
      confidence: 99,
      detectedTimestamp: '00:00:00 UTC',
      description: 'All 7 subsystems operating within normal baseline telemetry thresholds.',
    },
    aiPrediction: {
      potentialIssue: 'SYSTEM NOMINAL',
      probability: 2,
      estimatedTimeDays: 180,
      recommendedAction: 'Maintain current stationkeeping schedule and solar array tracking.',
    },
    subsystems: {
      power: {
        status: 'nominal',
        batteryCharge: 95,
        batteryVoltage: 28.4,
        batteryTemp: 18.5,
        solarOutput: 480,
        solarAngle: 12.4,
        solarEfficiency: 96.5,
        cycleCount: 1420,
        current: 16.9,
        powerConsumption: 450,
        powerDrawBreakdown: { aocs: 80, comm: 120, payload: 180, obc: 40, thermal: 30 },
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          batteryCharge: 92 + Math.floor(Math.sin(i / 2) * 4),
          solarOutput: 460 + Math.floor(Math.cos(i / 2) * 30),
          batteryVoltage: 28.2 + Number((Math.sin(i) * 0.3).toFixed(1)),
          temp: 18 + Number((Math.cos(i) * 0.5).toFixed(1)),
          current: 16.5 + Number((Math.sin(i) * 0.4).toFixed(1)),
          powerDraw: 445 + Math.floor(Math.sin(i) * 15),
        })),
      },
      thermal: {
        status: 'nominal',
        internalTemp: 21.2,
        externalTemp: -42.8,
        payloadTemp: 24.5,
        avionicsTemp: 26.1,
        heaterActive: false,
        radiatorStatus: 'Nominal',
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          internal: 20 + Math.random() * 2,
          external: -45 + Math.random() * 5,
          payload: 23 + Math.random() * 3,
        })),
      },
      aocs: {
        status: 'nominal',
        pitch: 1.2,
        yaw: -0.8,
        roll: 0.4,
        rxWheelSpeedX: 2450,
        rxWheelSpeedY: -2100,
        rxWheelSpeedZ: 1890,
        gyroStatus: 'OK',
        starTrackerStatus: 'Locked',
        altitude: 408,
        inclination: 51.6,
        eccentricity: 0.0005,
        periodMinutes: 92.6,
        groundStationPassCountdown: 252,
      },
      comm: {
        status: 'nominal',
        signalStrength: -68,
        snr: 28.5,
        uplinkRate: 10.4,
        downlinkRate: 150.0,
        antennaPointing: 'Optimal',
        contactWindowCountdown: 252,
        packetLoss: 0.01,
        bitErrorRate: 1e-8,
      },
      propulsion: {
        status: 'nominal',
        fuelLevel: 88.5,
        thrusterActive: false,
        lastFiring: '12d 4h ago',
        deltaVRemaining: 142.8,
        chamberPressure: 0.0,
      },
      payload: {
        status: 'nominal',
        operationalState: 'Active Imaging',
        dataStorageUsed: 42.8,
        solidStateDriveGB: 512,
        sensorHealth: { opticalSensor: true, syntheticApertureRadar: true, multispectralCamera: true },
      },
      obc: {
        status: 'nominal',
        cpuLoad: 24.5,
        memoryUsage: 38.2,
        uptimeSeconds: 842100,
        rebootCount: 1,
        softwareVersion: 'v3.8.4-RELEASE',
        watchdogState: 'Armed',
        lastCommand: 'TELEMETRY_DUMP_ALL',
        logs: [],
      },
    },
  },
  {
    id: 'SAT-002',
    name: 'SENTINEL-9',
    noradId: 43015,
    callsign: 'SN-09',
    orbitType: 'LEO',
    overallHealth: 91,
    healthStatus: 'nominal',
    position: { x: -3.8, y: 3.2, z: -1.2 },
    orbitRadius: 5.2,
    orbitSpeed: 0.006,
    orbitAngle: 2.1,
    inclination: 97.8,
    aiAnomaly: {
      detectedAnomaly: 'RF SIGNAL DEGRADATION',
      severity: 'LOW',
      confidence: 81,
      detectedTimestamp: '01:12:04 UTC',
      description: 'Downlink SNR fluctuation detected during high atmospheric noise corridor.',
    },
    aiPrediction: {
      potentialIssue: 'ANTENNA MISALIGNMENT',
      probability: 32,
      estimatedTimeDays: 28,
      recommendedAction: 'Recalibrate gimbal dish autotrack angle during next passes.',
    },
    subsystems: {
      power: {
        status: 'nominal',
        batteryCharge: 91,
        batteryVoltage: 27.8,
        batteryTemp: 22.1,
        solarOutput: 620,
        solarAngle: 4.2,
        solarEfficiency: 94.1,
        cycleCount: 2840,
        current: 22.3,
        powerConsumption: 580,
        powerDrawBreakdown: { aocs: 95, comm: 140, payload: 280, obc: 45, thermal: 60 },
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          batteryCharge: 89 + Math.floor(Math.sin(i / 3) * 3),
          solarOutput: 600 + Math.floor(Math.cos(i / 3) * 30),
          batteryVoltage: 27.6 + Number((Math.sin(i) * 0.2).toFixed(1)),
          temp: 22 + Number((Math.cos(i) * 0.3).toFixed(1)),
          current: 22 + Number((Math.sin(i) * 0.5).toFixed(1)),
          powerDraw: 575 + Math.floor(Math.sin(i) * 10),
        })),
      },
      thermal: {
        status: 'nominal',
        internalTemp: 28.4,
        externalTemp: 98.2,
        payloadTemp: 32.5,
        avionicsTemp: 30.1,
        heaterActive: false,
        radiatorStatus: 'Active Cooling',
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          internal: 27 + i * 0.1,
          external: 95 + Math.random() * 5,
          payload: 30 + i * 0.2,
        })),
      },
      aocs: {
        status: 'nominal',
        pitch: -0.5,
        yaw: 0.4,
        roll: -0.2,
        rxWheelSpeedX: 2900,
        rxWheelSpeedY: -2700,
        rxWheelSpeedZ: 2800,
        gyroStatus: 'OK',
        starTrackerStatus: 'Locked',
        altitude: 680,
        inclination: 97.8,
        eccentricity: 0.0012,
        periodMinutes: 98.4,
        groundStationPassCountdown: 866,
      },
      comm: {
        status: 'warning',
        signalStrength: -82,
        snr: 21.1,
        uplinkRate: 5.2,
        downlinkRate: 280.0,
        antennaPointing: 'Adjusting',
        contactWindowCountdown: 866,
        packetLoss: 0.04,
        bitErrorRate: 1e-7,
      },
      propulsion: {
        status: 'nominal',
        fuelLevel: 62.1,
        thrusterActive: false,
        lastFiring: '45d ago',
        deltaVRemaining: 98.2,
        chamberPressure: 0.0,
      },
      payload: {
        status: 'nominal',
        operationalState: 'Active Imaging',
        dataStorageUsed: 64.2,
        solidStateDriveGB: 1024,
        sensorHealth: { opticalSensor: true, syntheticApertureRadar: true, multispectralCamera: true },
      },
      obc: {
        status: 'nominal',
        cpuLoad: 42.1,
        memoryUsage: 54.1,
        uptimeSeconds: 1420900,
        rebootCount: 0,
        softwareVersion: 'v4.1.0-SOLAR',
        watchdogState: 'Armed',
        lastCommand: 'COMM_TUNE_RECEIVER',
        logs: [],
      },
    },
  },
  {
    id: 'SAT-003',
    name: 'ORBCOM-7',
    noradId: 38902,
    callsign: 'OB-07',
    orbitType: 'GEO',
    overallHealth: 84,
    healthStatus: 'warning',
    position: { x: 7.2, y: 0.2, z: -0.1 },
    orbitRadius: 7.2,
    orbitSpeed: 0.002,
    orbitAngle: 4.8,
    inclination: 0.1,
    aiAnomaly: {
      detectedAnomaly: 'SOLAR PANEL EFFICIENCY DROP',
      severity: 'MEDIUM',
      confidence: 94,
      detectedTimestamp: '02:34:18 UTC',
      description: 'Solar power bus voltage dropping due to partial array shadowing.',
    },
    aiPrediction: {
      potentialIssue: 'POWER SYSTEM DEGRADATION',
      probability: 68,
      estimatedTimeDays: 14,
      recommendedAction: 'Inspect solar-panel output and reduce non-essential power loads.',
    },
    subsystems: {
      power: {
        status: 'warning',
        batteryCharge: 87,
        batteryVoltage: 24.8,
        batteryTemp: 31.0,
        solarOutput: 820,
        solarAngle: 18.5,
        solarEfficiency: 82.0,
        cycleCount: 3100,
        current: 33.1,
        powerConsumption: 820,
        powerDrawBreakdown: { aocs: 110, comm: 450, payload: 180, obc: 40, thermal: 40 },
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          batteryCharge: 94 - i * 0.5,
          solarOutput: 950 - i * 9,
          batteryVoltage: 26.2 - Number((i * 0.1).toFixed(1)),
          temp: 26 + Number((i * 0.35).toFixed(1)),
          current: 30 + Number((i * 0.2).toFixed(1)),
          powerDraw: 800 + i * 2,
        })),
      },
      thermal: {
        status: 'warning',
        internalTemp: 34.2,
        externalTemp: -120.4,
        payloadTemp: 41.0,
        avionicsTemp: 35.8,
        heaterActive: false,
        radiatorStatus: 'Active Cooling',
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          internal: 28 + i * 0.4,
          external: -122 + Math.random() * 3,
          payload: 32 + i * 0.6,
        })),
      },
      aocs: {
        status: 'nominal',
        pitch: 0.8,
        yaw: -0.4,
        roll: 0.3,
        rxWheelSpeedX: 3800,
        rxWheelSpeedY: -3150,
        rxWheelSpeedZ: 2980,
        gyroStatus: 'OK',
        starTrackerStatus: 'Locked',
        altitude: 35786,
        inclination: 0.05,
        eccentricity: 0.0001,
        periodMinutes: 1436.0,
        groundStationPassCountdown: 0, // Continuous GEO link
      },
      comm: {
        status: 'nominal',
        signalStrength: -78,
        snr: 26.2,
        uplinkRate: 45.0,
        downlinkRate: 1200.0,
        antennaPointing: 'Optimal',
        contactWindowCountdown: 0,
        packetLoss: 0.0,
        bitErrorRate: 1e-9,
      },
      propulsion: {
        status: 'nominal',
        fuelLevel: 74.2,
        thrusterActive: false,
        lastFiring: '180d ago',
        deltaVRemaining: 310.0,
        chamberPressure: 0.0,
      },
      payload: {
        status: 'nominal',
        operationalState: 'Active Imaging',
        dataStorageUsed: 54.2,
        solidStateDriveGB: 2048,
        sensorHealth: { opticalSensor: true, syntheticApertureRadar: true, multispectralCamera: true },
      },
      obc: {
        status: 'nominal',
        cpuLoad: 58.4,
        memoryUsage: 62.9,
        uptimeSeconds: 3412000,
        rebootCount: 0,
        softwareVersion: 'v5.0.1-GEOCOMM',
        watchdogState: 'Armed',
        lastCommand: 'POWER_BUS_OPTIMIZE',
        logs: [],
      },
    },
  },
  {
    id: 'SAT-004',
    name: 'HELIOS-1',
    noradId: 51094,
    callsign: 'HL-01',
    orbitType: 'LEO',
    overallHealth: 98,
    healthStatus: 'nominal',
    position: { x: 2.1, y: -4.1, z: 2.2 },
    orbitRadius: 5.0,
    orbitSpeed: 0.009,
    orbitAngle: 5.2,
    inclination: 82.4,
    aiAnomaly: {
      detectedAnomaly: 'NO ANOMALY DETECTED',
      severity: 'LOW',
      confidence: 99,
      detectedTimestamp: '00:00:00 UTC',
      description: 'SAR imaging antenna and power distribution bus operating within nominal envelope.',
    },
    aiPrediction: {
      potentialIssue: 'SYSTEM STABLE',
      probability: 2,
      estimatedTimeDays: 240,
      recommendedAction: 'Routine calibration scheduled at next Svalbard ground station pass.',
    },
    subsystems: {
      power: {
        status: 'nominal',
        batteryCharge: 95,
        batteryVoltage: 28.5,
        batteryTemp: 19.8,
        solarOutput: 780,
        solarAngle: 48.2,
        solarEfficiency: 41.2,
        cycleCount: 3190,
        current: 41.2,
        powerConsumption: 910,
        powerDrawBreakdown: { aocs: 150, comm: 110, payload: 40, obc: 50, thermal: 80 },
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          batteryCharge: 60 - i * 1.5,
          solarOutput: 320 - i * 8,
          batteryVoltage: 25.0 - Number((i * 0.2).toFixed(1)),
          temp: 30 + Number((i * 0.65).toFixed(1)),
          current: 35 + Number((i * 0.4).toFixed(1)),
          powerDraw: 850 + i * 4,
        })),
      },
      thermal: {
        status: 'warning',
        internalTemp: 39.4,
        externalTemp: -20.1,
        payloadTemp: 48.2,
        avionicsTemp: 43.1,
        heaterActive: true,
        radiatorStatus: 'Degraded',
        history: Array.from({ length: 15 }, (_, i) => ({
          time: `${i * 2}m ago`,
          internal: 30 + i * 0.6,
          external: -30 + i * 0.7,
          payload: 38 + i * 0.7,
        })),
      },
      aocs: {
        status: 'critical',
        pitch: 14.8,
        yaw: -18.2,
        roll: 32.1,
        rxWheelSpeedX: 5800,
        rxWheelSpeedY: -4900,
        rxWheelSpeedZ: 6100,
        gyroStatus: 'Degraded',
        starTrackerStatus: 'Searching',
        altitude: 520,
        inclination: 82.4,
        eccentricity: 0.0045,
        periodMinutes: 94.8,
        groundStationPassCountdown: 180,
      },
      comm: {
        status: 'warning',
        signalStrength: -98,
        snr: 11.2,
        uplinkRate: 2.1,
        downlinkRate: 12.0,
        antennaPointing: 'Misaligned',
        contactWindowCountdown: 180,
        packetLoss: 8.4,
        bitErrorRate: 1e-4,
      },
      propulsion: {
        status: 'nominal',
        fuelLevel: 41.5,
        thrusterActive: false,
        lastFiring: '3d ago',
        deltaVRemaining: 54.0,
        chamberPressure: 0.0,
      },
      payload: {
        status: 'warning',
        operationalState: 'Standby',
        dataStorageUsed: 82.1,
        solidStateDriveGB: 512,
        sensorHealth: { opticalSensor: false, syntheticApertureRadar: true, multispectralCamera: false },
      },
      obc: {
        status: 'warning',
        cpuLoad: 88.5,
        memoryUsage: 82.4,
        uptimeSeconds: 98100,
        rebootCount: 4,
        softwareVersion: 'v2.9.1-SAFE_MODE',
        watchdogState: 'Triggered',
        lastCommand: 'AOCS_FORCE_SAFE_HOLD',
        logs: [],
      },
    },
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-101',
    timestamp: '2m ago',
    satelliteId: 'SAT-002',
    satelliteName: 'SENTINEL-9',
    subsystem: 'power',
    severity: 'critical',
    title: 'Battery Anomaly',
    message: 'Battery voltage dropping below threshold. Deep discharge risk.',
    acknowledged: false,
    resolved: false,
  },
  {
    id: 'ALT-102',
    timestamp: '8m ago',
    satelliteId: 'SAT-004',
    satelliteName: 'HELIOS-1',
    subsystem: 'thermal',
    severity: 'warning',
    title: 'High Temperature',
    message: 'Payload temperature above nominal range (59.8°C). Active heat rejection required.',
    acknowledged: false,
    resolved: false,
  },
  {
    id: 'ALT-103',
    timestamp: '12m ago',
    satelliteId: 'SAT-003',
    satelliteName: 'ORBCOM-7',
    subsystem: 'comm',
    severity: 'info',
    title: 'Ground Pass',
    message: 'Next ground pass in 12 minutes with GS-New Delhi.',
    acknowledged: true,
    resolved: false,
  },
  {
    id: 'ALT-104',
    timestamp: '18m ago',
    satelliteId: 'SAT-001',
    satelliteName: 'AGIS-3',
    subsystem: 'obc',
    severity: 'info',
    title: 'Mode Transition',
    message: 'Entering safe mode for calibration and sensor alignment.',
    acknowledged: true,
    resolved: false,
  },
];

export function computeOverallHealth(satellite: Satellite): { score: number; status: HealthStatus } {
  const subs = satellite.subsystems;
  let criticalCount = 0;
  let warningCount = 0;

  (Object.keys(subs) as (keyof typeof subs)[]).forEach((key) => {
    if (subs[key].status === 'critical') criticalCount++;
    else if (subs[key].status === 'warning') warningCount++;
  });

  let score = 100 - criticalCount * 25 - warningCount * 10;
  score = Math.max(5, Math.min(100, score));

  let status: HealthStatus = 'nominal';
  if (criticalCount > 0 || score < 70) {
    status = 'critical';
  } else if (warningCount > 0 || score < 90) {
    status = 'warning';
  }

  return { score, status };
}
